stages:
  - checkLintPython
  - checkLintCpp

lint_black:
  stage: checkLintPython
  image: python:3.10
  before_script:
    - pip install black
  script:
    - black --check --diff .
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      changes:
        - "*.py"
        - "**/*.py"

lint_cpp:
  stage: checkLintCpp
  image: gcc:latest
  before_script:
    - apt-get update
    - apt-get install -y cppcheck
  script:
    - cppcheck --enable=all --inconclusive --error-exitcode=1 .
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      changes:
        - "*.cpp"
        - "**/*.cpp"
