<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>iros_mobile_platform_database</name>
  <version>0.0.0</version>
  <description>A ROS2 package to manage maps, points, and routes in a MongoDB database.</description>
  <maintainer email="i.domrachev@innopolis.university">dom-iva</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <build_depend>rosidl_default_generators</build_depend>

  <depend>geometry_msgs</depend>
  <depend>nav2_msgs</depend>
  <depend>rclpy</depend>
  <depend>nav_msgs</depend>
  <depend>iros_mobile_platform_database_msgs</depend>

  <exec_depend>pymongo</exec_depend>
  <exec_depend>python3-pil</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
